In [1]:
import sympy as sp

# Define the variables
t, mu, sigma = sp.symbols('t mu sigma')

# Define the MGF of a normal distribution
MGF = sp.exp(t*mu + 0.5 * sigma**2 * t**2)

# Compute the derivatives
first_derivative = sp.diff(MGF, t)
second_derivative = sp.diff(MGF, t, 2)
third_derivative = sp.diff(MGF, t, 3)
fourth_derivative = sp.diff(MGF, t, 4)

# Evaluate the derivatives at t = 0
E_X = first_derivative.subs(t, 0)
E_X2 = second_derivative.subs(t, 0)
E_X3 = third_derivative.subs(t, 0)
E_X4 = fourth_derivative.subs(t, 0)

# Display the results
print(f"E[X] = {E_X}")
print(f"E[X^2] = {E_X2}")
print(f"E[X^3] = {E_X3}")
print(f"E[X^4] = {E_X4}")

E[X] = mu
E[X^2] = mu**2 + 1.0*sigma**2
E[X^3] = mu*(mu**2 + 3.0*sigma**2)
E[X^4] = mu**4 + 6.0*mu**2*sigma**2 + 3.0*sigma**4


In [2]:
import sympy as sp

# Define the variables
mu, sigma = sp.symbols('mu sigma')

# E[X^2] = mu^2 + sigma^2
E_X2 = mu**2 + sigma**2

# E[X^4] = mu^4 + 6*mu^2*sigma^2 + 3*sigma^4
E_X4 = mu**4 + 6*mu**2*sigma**2 + 3*sigma**4

# Calculate Var(X^2)
Var_X2 = E_X4 - E_X2**2

# Simplify and display the result
Var_X2_simplified = sp.simplify(Var_X2)
print(f"Var(X^2) = {Var_X2_simplified}")


Var(X^2) = 2*sigma**2*(2*mu**2 + sigma**2)


In [7]:
import numpy as np

a=np.array([[8,4,7],[2,8,1],[3,1,1],[9,7,4]]).T
print(a)
np.cov(a,ddof=0)

[[8 2 3 9]
 [4 8 1 7]
 [7 1 1 4]]


array([[9.25  , 1.    , 6.375 ],
       [1.    , 7.5   , 0.    ],
       [6.375 , 0.    , 6.1875]])